package com.interact.listen.stats;

import com.interact.insa.client.StatId;

/**
 * Statistics specific to the Listen application. Each {@code Stat} is associated with its corresponding {@link StatId}
 * constant.
 */
public enum Stat
{
    API_CONFERENCE_DELETE(StatId.LISTEN_CONTROLLER_API_CONFERENCE_DELETE),
    API_CONFERENCE_GET(StatId.LISTEN_CONTROLLER_API_CONFERENCE_GET),
    API_CONFERENCE_POST(StatId.LISTEN_CONTROLLER_API_CONFERENCE_POST),
    API_CONFERENCE_PUT(StatId.LISTEN_CONTROLLER_API_CONFERENCE_PUT),

    API_CONFERENCEHISTORY_DELETE(StatId.LISTEN_CONTROLLER_API_CONFERENCEHISTORY_DELETE),
    API_CONFERENCEHISTORY_GET(StatId.LISTEN_CONTROLLER_API_CONFERENCEHISTORY_GET),
    API_CONFERENCEHISTORY_POST(StatId.LISTEN_CONTROLLER_API_CONFERENCEHISTORY_POST),
    API_CONFERENCEHISTORY_PUT(StatId.LISTEN_CONTROLLER_API_CONFERENCEHISTORY_PUT),

    API_LISTENSPOTSUBSCRIBER_DELETE(StatId.LISTEN_CONTROLLER_API_LISTENSPOTSUBSCRIBER_DELETE),
    API_LISTENSPOTSUBSCRIBER_GET(StatId.LISTEN_CONTROLLER_API_LISTENSPOTSUBSCRIBER_GET),
    API_LISTENSPOTSUBSCRIBER_POST(StatId.LISTEN_CONTROLLER_API_LISTENSPOTSUBSCRIBER_POST),
    API_LISTENSPOTSUBSCRIBER_PUT(StatId.LISTEN_CONTROLLER_API_LISTENSPOTSUBSCRIBER_PUT),

    API_PARTICIPANT_DELETE(StatId.LISTEN_CONTROLLER_API_PARTICIPANT_DELETE),
    API_PARTICIPANT_GET(StatId.LISTEN_CONTROLLER_API_PARTICIPANT_GET),
    API_PARTICIPANT_POST(StatId.LISTEN_CONTROLLER_API_PARTICIPANT_POST),
    API_PARTICIPANT_PUT(StatId.LISTEN_CONTROLLER_API_PARTICIPANT_PUT),

    API_PIN_DELETE(StatId.LISTEN_CONTROLLER_API_PIN_DELETE),
    API_PIN_GET(StatId.LISTEN_CONTROLLER_API_PIN_GET),
    API_PIN_POST(StatId.LISTEN_CONTROLLER_API_PIN_POST),
    API_PIN_PUT(StatId.LISTEN_CONTROLLER_API_PIN_PUT),

    API_SUBSCRIBER_DELETE(StatId.LISTEN_CONTROLLER_API_SUBSCRIBER_DELETE),
    API_SUBSCRIBER_GET(StatId.LISTEN_CONTROLLER_API_SUBSCRIBER_GET),
    API_SUBSCRIBER_POST(StatId.LISTEN_CONTROLLER_API_SUBSCRIBER_POST),
    API_SUBSCRIBER_PUT(StatId.LISTEN_CONTROLLER_API_SUBSCRIBER_PUT),

    API_USER_DELETE(StatId.LISTEN_CONTROLLER_API_USER_DELETE),
    API_USER_GET(StatId.LISTEN_CONTROLLER_API_USER_GET),
    API_USER_POST(StatId.LISTEN_CONTROLLER_API_USER_POST),
    API_USER_PUT(StatId.LISTEN_CONTROLLER_API_USER_PUT),

    API_VOICEMAIL_DELETE(StatId.LISTEN_CONTROLLER_API_VOICEMAIL_DELETE),
    API_VOICEMAIL_GET(StatId.LISTEN_CONTROLLER_API_VOICEMAIL_GET),
    API_VOICEMAIL_POST(StatId.LISTEN_CONTROLLER_API_VOICEMAIL_POST),
    API_VOICEMAIL_PUT(StatId.LISTEN_CONTROLLER_API_VOICEMAIL_PUT),

    GUI_DROP_PARTICIPANT(StatId.LISTEN_CONTROLLER_GUI_DROP_PARTICIPANT),
    GUI_GET_CONFERENCE_INFO(StatId.LISTEN_CONTROLLER_GUI_GET_CONFERENCE_INFO),
    GUI_LOGIN(StatId.LISTEN_CONTROLLER_GUI_LOGIN),
    GUI_LOGOUT(StatId.LISTEN_CONTROLLER_GUI_LOGOUT),
    GUI_MUTE_PARTICIPANT(StatId.LISTEN_CONTROLLER_GUI_MUTE_PARTICIPANT),
    GUI_PROVISION_ACCOUNT(StatId.LISTEN_CONTROLLER_GUI_PROVISION_ACCOUNT),
    GUI_UNMUTE_PARTICIPANT(StatId.LISTEN_CONTROLLER_GUI_UNMUTE_PARTICIPANT),
    GUI_SCHEDULE_CONFERENCE(StatId.LISTEN_CONTROLLER_GUI_SCHEDULE_CONFERENCE),
    GUI_OUTDIAL(StatId.LISTEN_CONTROLLER_GUI_OUTDIAL_PARTICIPANT),

    PUBLISHED_EVENT_TO_SPOT(StatId.LISTEN_CONTROLLER_PUBLISHED_EVENT_TO_SPOT),
    ADMIN_PARTICIPANT_JOIN(StatId.LISTEN_CONTROLLER_ADMIN_PARTICIPANT_JOIN),
    ACTIVE_PARTICIPANT_JOIN(StatId.LISTEN_CONTROLLER_ACTIVE_PARTICIPANT_JOIN),
    PASSIVE_PARTICIPANT_JOIN(StatId.LISTEN_CONTROLLER_PASSIVE_PARTICIPANT_JOIN),
    CONFERENCE_START(StatId.LISTEN_CONTROLLER_CONFERENCE_START),
    CONFERENCE_LENGTH(StatId.LISTEN_CONTROLLER_CONFERENCE_LENGTH);

    private String statId;
    private Stat(String statId)
    {
        this.statId = statId;
    }

    public String getStatId()
    {
        return statId;
    }
}
