#!/bin/bash
#
# listen-controller      Start/Stop listen-controller
#
# chkconfig: 345 62 38
# description: listen-controller is part of the Interact Listen solution
#
# processname: java
#
# By: Nick Walter - waltern@iivip.com
#

. /etc/init.d/functions
. /etc/sysconfig/network

RETVAL=0
ORETVAL=0

if [ -z $LISTEN_HOME ]; then
LISTEN_HOME=/interact/listen
fi

start() {
    if [ -f /var/lock/subsys/listen-controller ]; then
        echo -n $"Listen-controller already running with pid `cat /var/run/listen-controller.pid`"
        failure
        echo
        exit
    fi
   
    echo -n $"Starting listen-controller: "
    # Start me up!
    java -Dport=9091 -Dcom.interact.listen.env=PROD -Dext=`find /interact -iname 'mysql-connector-*.jar' -type 'f' | head -1` -Dcom.interact.listen.logDir=/interact/listen/logs -jar $LISTEN_HOME/lib/listen-controller.war <&- 1>/interact/listen/logs/listen-controller.console 2>&1 &
    RETVAL=$?
    JPID=$!
    echo $JPID > /var/run/listen-controller.pid
    [ $RETVAL -eq 0 ] && success
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/listen-controller
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping listen-controller: "
    killproc -p /var/run/listen-controller.pid java
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/listen-controller
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  status)
    status listen-controller
    ;;
  restart)
      restart
    ;;
  condrestart)
      [ -f /var/lock/subsys/listen-controller ] && restart || :
    ;;
  reload)
    reload
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
    exit 1
esac

exit $?

