#!/bin/bash
#
# listen-gui      Start/Stop listen-gui
#
# chkconfig: 345 62 38
# description: listen-gui is part of the Interact Listen solution
#
# processname: java
#
# By: Nick Walter - waltern@iivip.com
#

. /etc/init.d/functions
. /etc/sysconfig/network

RETVAL=0
ORETVAL=0

if [ -z $LISTEN_HOME ]; then
LISTEN_HOME=/interact/listen
fi

start() {
    if [ -f /var/lock/subsys/listen-gui ]; then
        echo -n $"Listen-gui already running with pid `cat /var/run/listen-gui.pid`"
        failure
        echo
        exit
    fi
   
    echo -n $"Starting listen-gui: "
    # Start me up!
    java -jar $LISTEN_HOME/lib/listen-gui.jar --httpPort=9096 --ajp13Port=9097  --logfile=/interact/listen/logs/listen-gui.console <&- 1>/dev/null 2>&1 &
    RETVAL=$?
    JPID=$!
    echo $JPID > /var/run/listen-gui.pid
    [ $RETVAL -eq 0 ] && success
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/listen-gui
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping listen-gui: "
    killproc -p /var/run/listen-gui.pid java
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/listen-gui
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  status)
    status listen-gui
    ;;
  restart)
      restart
    ;;
  condrestart)
      [ -f /var/lock/subsys/listen-gui ] && restart || :
    ;;
  reload)
    reload
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
    exit 1
esac

exit $?

